name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: RASPBERRY_PI_HOST

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Debug Deployment
        run: |
          # Debugging: Show current user and environment
          echo "Current user: $(whoami)"
          echo "Home directory: $HOME"
          ls -la $HOME
          echo "Environment Variables:"
          env

      - name: Deploy to Raspberry Pi
        run: |
          # Ensure the SSH directory exists
          mkdir -p ~/.ssh
          echo "SSH directory created: $(ls -la ~/.ssh)"

          # Write the private SSH key to the SSH directory
          echo "${{ secrets.RASPBERRY_PI_SECRET_KEY }}" > ~/.ssh/github_actions
          chmod 600 ~/.ssh/github_actions
          echo "SSH key file created: $(ls -la ~/.ssh)"

          # Add the Raspberry Pi's host key to known hosts
          ssh-keyscan -p 2222 ${{ secrets.RASPI_HOST }} >> ~/.ssh/known_hosts
          echo "Known hosts updated: $(cat ~/.ssh/known_hosts)"

          # SSH into Raspberry Pi and execute commands
          ssh -v -i ~/.ssh/github_actions -p 2222 pi@${{ secrets.RASPI_HOST }} << EOF
            cd /var/www/html/repos/portfolio_website || exit 1
            git pull origin main || exit 1

            # Install dependencies and build the application
            npm install || exit 1
            npm run build || exit 1

            # Move built files to the Nginx served directory
            rm -rf /var/www/html/portfolio-website/* || exit 1
            mv dist/* /var/www/html/portfolio-website/ || exit 1

            # Restart Nginx
            sudo systemctl restart nginx || exit 1
          EOF