name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: RASPBERRY_PI_HOST

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Debug Deployment
        run: |
          # Debugging: Show current user and environment
          echo "Current user: $(whoami)"
          echo "Home directory: $HOME"
          echo "Environment Variables:"
          env

          # Ensure the SSH directory exists
          mkdir -p ~/.ssh
          echo "SSH directory contents:"
          ls -la ~/.ssh

          # Write the private SSH key to the SSH directory
          echo "${{ secrets.RASPBERRY_PI_SECRET_KEY }}" > ~/.ssh/github_actions
          chmod 600 ~/.ssh/github_actions
          echo "SSH key file created:"
          ls -la ~/.ssh

          # Add the Raspberry Pi's host key to known hosts
          ssh-keyscan -v -p 2222 ${{ secrets.RASPI_HOST }} >> ~/.ssh/known_hosts
          echo "Known hosts file contents:"
          cat ~/.ssh/known_hosts

      - name: Test SSH Connection
        run: |
          # Test SSH connection with verbose output
          ssh -vvv -i ~/.ssh/github_actions -p 2222 pi@${{ secrets.RASPI_HOST }} exit

      - name: Deploy to Raspberry Pi
        run: |
          # SSH into Raspberry Pi and execute commands
          ssh -i ~/.ssh/github_actions -p 2222 pi@${{ secrets.RASPI_HOST }} << EOF
            set -e
            cd /var/www/html/repos/portfolio_website
            git pull origin main

            # Install dependencies and build the application
            npm install
            npm run build

            # Move built files to the Nginx served directory
            rm -rf /var/www/html/portfolio-website/*
            mv dist/* /var/www/html/portfolio-website/

            # Restart Nginx
            sudo systemctl restart nginx
          EOF