name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: RASPBERRY_PI_HOST

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to Raspberry Pi
        run: |
          # Write the private SSH key to a file
          echo "${{ secrets.RASPBERRY_PI_SECRET_KEY }}" > ~/.ssh/github_actions
          chmod 600 ~/.ssh/github_actions

          # Add the Raspberry Pi's host key to known hosts
          ssh-keyscan -p 2222 ${{ secrets.RASPI_HOST }} >> ~/.ssh/known_hosts

          # SSH into Raspberry Pi and execute commands
          ssh -i ~/.ssh/github_actions -p 2222 pi@${{ secrets.RASPI_HOST }} << EOF
            cd /var/www/html/repos/portfolio_website
            git pull origin main

            # Install dependencies and build the application
            npm install
            npm run build

            # Move built files to the Nginx served directory
            rm -rf /var/www/html/portfolio-website/*
            mv dist/* /var/www/html/portfolio-website/

            # Restart Nginx
            sudo systemctl restart nginx
          EOF