name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: RASPBERRY_PI_HOST  # Specify the environment here

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to Raspberry Pi
        run: |
          # SSH into Raspberry Pi and execute the deployment commands
          ssh -i <(echo "${{ secrets.RASPBERRY_PI_SECRET_KEY }}") -p 2222 pi@${{secrets.RASPI_HOST}} << EOF
            cd $REPO_PATH
            git pull origin main

            # Install dependencies and build the application
            npm install
            npm run build

            # Move built files to the Nginx served directory
            rm -rf $NGINX_PATH/*
            mv dist/* $NGINX_PATH/

            # Restart Nginx to serve the updated files (if necessary)
            sudo systemctl restart nginx
          EOF