name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to Raspberry Pi
        env:
            PI_HOST: ${{ secrets.RASPI_HOST }}  # Raspberry Pi IP address as a secret
            # PI_USER: pi
            REPO_PATH: /var/www/html/repos/portfolio_website
            NGINX_PATH: /var/www/html/portfolio-website
        run: |
          # SSH into Raspberry Pi and execute the deployment commands
          ssh -i <(echo "${{ secrets.RASPBERRY_PI_SECRET_KEY }}") pi@$PI_HOST -p 2222 << EOF
            cd $REPO_PATH
            git pull origin main

            # Install dependencies and build the application
            npm install
            npm run build

            # Move built files to the Nginx served directory
            rm -rf $NGINX_PATH/*
            mv dist/* $NGINX_PATH/

            # Restart Nginx to serve the updated files (if necessary)
            sudo systemctl restart nginx
          EOF