name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: RASPBERRY_PI_HOST

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to Raspberry Pi
        run: |
          # Ensure the SSH directory exists
          mkdir -p /home/runner/.ssh
          chmod 700 /home/runner/.ssh

          # Write the private SSH key to the SSH directory
          echo "${{ secrets.RASPBERRY_PI_SECRET_KEY }}" > /home/runner/.ssh/github_actions
          chmod 600 /home/runner/.ssh/github_actions

          # Add the Raspberry Pi's host key to known_hosts
          ssh-keyscan -p 2222 ${{ secrets.RASPI_HOST }} >> /home/runner/.ssh/known_hosts

          # Debugging: Show SSH directory contents
          ls -la /home/runner/.ssh

          # SSH into Raspberry Pi and execute commands
          ssh -i /home/runner/.ssh/github_actions -p 2222 pi@${{ secrets.RASPI_HOST }} << EOF
            set -e
            cd /var/www/html/repos/portfolio_website
            git pull origin main

            # Install dependencies and build the application
            npm install
            npm run build

            # Move built files to the Nginx served directory
            rm -rf /var/www/html/portfolio-website/*
            mv dist/* /var/www/html/portfolio-website/

            # Restart Nginx
            sudo systemctl restart nginx
          EOF